import { NextResponse } from 'next/server';

// Tag options matching the Gradio API specification
const TAG_OPTIONS = {
  occasion: [
    "casual",
    "business",
    "formal",
    "semi_formal",
    "business_casual",
    "cocktail",
    "wedding",
    "party",
    "date",
    "sport",
    "workout",
    "travel",
    "beach",
    "outdoor",
    "night_out",
    "brunch",
    "dinner",
    "meeting",
    "interview",
    "cultural",
    "traditional",
  ],
  weather: [
    "any",
    "hot",
    "warm",
    "mild",
    "cool",
    "cold",
    "freezing",
    "rain",
    "snow",
    "windy",
    "humid",
    "sunny",
    "cloudy",
  ],
  outfit_style: [
    "casual",
    "smart_casual",
    "formal",
    "sporty",
    "athletic",
    "streetwear",
    "minimalist",
    "classic",
    "modern",
    "elegant",
    "sophisticated",
    "traditional",
    "ethnic",
  ],
  color_preference: [
    "None",
    "neutral",
    "monochromatic",
    "monochrome",
    "complementary",
    "bold",
    "subtle",
    "bright",
    "muted",
    "pastel",
    "dark",
    "light",
    "earth_tones",
    "jewel_tones",
    "black_white",
    "navy_white",
    "colorful",
    "minimal_color",
  ],
  fit_preference: [
    "None",
    "fitted",
    "loose",
    "oversized",
    "relaxed",
    "comfortable",
    "structured",
    "flowy",
    "tailored",
    "athletic_fit",
    "regular_fit",
  ],
  material_preference: [
    "None",
    "cotton",
    "linen",
    "silk",
    "wool",
    "cashmere",
    "denim",
    "leather",
    "breathable",
    "waterproof",
    "moisture_wicking",
    "sustainable",
  ],
  season: [
    "None",
    "spring",
    "summer",
    "fall",
    "autumn",
    "winter",
    "year_round",
    "transitional",
  ],
  time_of_day: [
    "None",
    "morning",
    "afternoon",
    "evening",
    "night",
    "all_day",
  ],
  budget: [
    "None",
    "luxury",
    "premium",
    "mid_range",
    "affordable",
    "budget",
    "value",
  ],
  personal_style: [
    "None",
    "conservative",
    "moderate",
    "bold",
    "experimental",
    "traditional",
    "trendy",
    "timeless",
    "fashion_forward",
    "classic",
    "eclectic",
  ],
};

export async function GET() {
  try {
    return NextResponse.json({
      success: true,
      data: TAG_OPTIONS,
    });
  } catch (error) {
    console.error('Error fetching tags:', error);
    return NextResponse.json(
      { error: 'Failed to fetch tags' },
      { status: 500 }
    );
  }
}


